SELECT H.NOM_H 
FROM HOSPITAL H,CIUDAD C 
WHERE H.COD_C=C.COD_C 
AND C.NOM_C="BILBAO"

//NOMBRE DE TODOS LOS MEDICOS Y DONDE TRABAJAN
SELECT M.NOM_M ,H.NOM_H
FROM MEDICOS M, HOSPITAL H
LEFT JOIN H.COD_H=M.NOM_H 
GROUP BY M.NOM_M